"""
Seed dataset tiếng Việt cho Text Moderation Model.
Labels: 0 = SAFE, 1 = TOXIC, 2 = SPAM
~500 mẫu để train model cold-start.
"""

SEED_DATA: list[tuple[str, int]] = [
    # ─── SAFE (label=0) ─────────────────────────────────────────────────────────
    ("Sản phẩm rất tốt, giao hàng nhanh", 0),
    ("Chất lượng ổn với giá tiền", 0),
    ("Mình rất hài lòng với đơn hàng này", 0),
    ("Đóng gói cẩn thận, hàng đúng mô tả", 0),
    ("Shop giao hàng nhanh, sản phẩm chất lượng tốt", 0),
    ("Hàng đẹp, đúng mô tả, giao nhanh", 0),
    ("Mua lần 2 rồi vẫn hài lòng", 0),
    ("Sản phẩm tốt, giá hợp lý", 0),
    ("Giao hàng đúng hẹn, hàng chắc chắn", 0),
    ("Tuyệt vời, sẽ mua lại", 0),
    ("Hàng đẹp hơn mình tưởng", 0),
    ("Sản phẩm chất lượng cao, đáng tiền", 0),
    ("Mua về dùng thử thấy ổn lắm", 0),
    ("Shop nhiệt tình, hàng tốt", 0),
    ("Sản phẩm y hình, dùng được", 0),
    ("Chất vải tốt, màu sắc đẹp", 0),
    ("Pin trâu, dùng cả ngày không hết", 0),
    ("Điện thoại chạy nhanh, màn hình đẹp", 0),
    ("Laptop chạy mượt, bàn phím êm", 0),
    ("Tai nghe âm thanh hay, bass tốt", 0),
    ("Đồng hồ đẹp, chính xác, đeo thoải mái", 0),
    ("Giày vừa chân, chất liệu tốt", 0),
    ("Áo mặc mát, không bai xù", 0),
    ("Nồi cơm điện nấu chín đều, ít tốn điện", 0),
    ("Máy lọc nước tốt, lắp đặt dễ dàng", 0),
    ("Sữa tươi ngon, con uống thích lắm", 0),
    ("Dầu gội thơm, tóc mềm sau khi gội", 0),
    ("Son môi màu đẹp, giữ màu lâu", 0),
    ("Kem dưỡng da nhẹ, thấm nhanh", 0),
    ("Balo đựng được nhiều đồ, chất liệu bền", 0),
    ("Ví da đẹp, may chắc chắn", 0),
    ("Kính mắt nhẹ, gọng chắc", 0),
    ("Đồ chơi an toàn cho bé, bé thích lắm", 0),
    ("Sách hay, in rõ, bìa cứng", 0),
    ("Chuột không dây dùng tốt, pin lâu", 0),
    ("Bàn phím cơ gõ sướng", 0),
    ("Màn hình hiển thị màu chuẩn", 0),
    ("Camera chụp ảnh đẹp ngoài trời", 0),
    ("Loa bluetooth âm thanh hay", 0),
    ("Sạc dự phòng đầy đủ cổng, sạc nhanh", 0),
    ("Ốp lưng vừa máy, bảo vệ tốt", 0),
    ("Cáp sạc bền, không bị đứt", 0),
    ("Tủ lạnh giữ lạnh tốt, ít tiếng ồn", 0),
    ("Máy giặt giặt sạch, ít tốn nước", 0),
    ("Nệm êm, ngủ ngon", 0),
    ("Ghế công thái học ngồi thoải mái", 0),
    ("Bàn làm việc chắc chắn, lắp ráp dễ", 0),
    ("Đèn học sáng vừa, không chói mắt", 0),
    ("Chảo không dính tốt, dễ rửa", 0),
    ("Bình nước giữ nhiệt tốt cả ngày", 0),
    ("Cốc cafe giữ nóng lâu, thiết kế đẹp", 0),
    ("Thảm yoga dày, chống trượt tốt", 0),
    ("Tạ tập tay nặng vừa, không bị han gỉ", 0),
    ("Xe đạp lắp nhanh, chạy êm", 0),
    ("Mũ bảo hiểm vừa đầu, nhẹ", 0),
    ("Xử lý đơn nhanh, shipper lịch sự", 0),
    ("Đóng hàng kỹ, không bị vỡ", 0),
    ("Hỗ trợ khách hàng nhiệt tình", 0),
    ("Đổi trả dễ dàng, shop uy tín", 0),
    ("Giao hàng siêu tốc, cảm ơn shop", 0),
    ("Nhận hàng đúng hẹn, đóng gói đẹp", 0),
    ("Hàng nguyên seal, chính hãng", 0),
    ("Sản phẩm đúng như quảng cáo", 0),
    ("Mua lần đầu đã rất ưng", 0),
    ("Chất lượng vượt mong đợi", 0),
    ("Giá rẻ mà chất lượng tốt", 0),
    ("Mẫu đẹp, nhiều màu chọn", 0),
    ("Size đúng như bảng size hướng dẫn", 0),
    ("Màu sắc giống hình, không bị lệch", 0),
    ("Dùng thử 1 tuần vẫn tốt", 0),
    ("Hài lòng, sẽ giới thiệu cho bạn bè", 0),
    ("Mua nhiều lần chưa bao giờ thất vọng", 0),
    ("Đặt hàng dễ, thanh toán thuận tiện", 0),
    ("Ứng dụng dễ dùng, tìm hàng nhanh", 0),
    ("Voucher giảm giá tốt, tiết kiệm được nhiều", 0),
    ("Freeship nên mua thêm nhiều thứ luôn", 0),
    ("Flash sale giá rẻ, mua ngay", 0),
    ("Sản phẩm hot, bán chạy có lý do", 0),
    ("Review chuẩn, mua đúng như kỳ vọng", 0),
    ("Tin tưởng shop lâu năm", 0),
    ("Hàng chuẩn auth, có bill đầy đủ", 0),
    ("Mùi thơm dễ chịu, không quá nồng", 0),
    ("Dung tích lớn, dùng được lâu", 0),
    ("Thành phần an toàn, phù hợp da nhạy cảm", 0),
    ("Da mặt căng mịn sau khi dùng", 0),
    ("Hiệu quả sau 2 tuần sử dụng", 0),
    ("Giảm mụn rõ rệt sau 1 tháng", 0),
    ("Không gây kích ứng, phù hợp mọi loại da", 0),
    ("Tóc bóng mượt, ít rụng hơn", 0),
    ("Nước hoa nhẹ nhàng, phù hợp đi làm", 0),
    ("Son dưỡng mềm môi, không bong tróc", 0),
    ("Phấn phủ mịn, không bí da", 0),
    ("Mascara không lem, giữ lâu", 0),
    ("Bộ dưỡng da đầy đủ bước, tiện lợi", 0),
    ("Ánh sáng tốt, chụp ảnh đẹp", 0),
    ("Pin sạc đầy nhanh, dùng lâu", 0),
    ("Cảm ứng nhạy, không bị lag", 0),
    ("Màn hình Full HD sắc nét", 0),
    ("Âm thanh stereo rõ ràng", 0),
    ("Camera kép chụp xóa phông đẹp", 0),
    ("Thiết kế mỏng nhẹ, cầm vừa tay", 0),
    ("Kết nối wifi nhanh ổn định", 0),
    ("Bluetooth 5.0 kết nối nhanh", 0),
    ("NFC tiện dùng thanh toán", 0),
    ("Loa ngoài to rõ", 0),
    ("Jack tai nghe âm thanh trong trẻo", 0),
    ("Rất ok, mình thích lắm", 0),
    ("Dùng được rồi, chất lượng chấp nhận được", 0),
    ("Không hào hứng lắm nhưng dùng tạm ổn", 0),
    ("Hàng bình thường, không có gì đặc biệt", 0),
    ("Tạm ổn, không quá kỳ vọng", 0),
    ("Chất lượng trung bình, giá cũng trung bình", 0),
    ("Phù hợp với túi tiền sinh viên", 0),
    ("Mua làm quà tặng, người nhận thích", 0),
    ("Gói quà đẹp, tặng bạn gái rất vui", 0),
    ("Sản phẩm mới, chưa dùng nhưng nhìn ok", 0),
    ("Đóng gói đẹp, bảo quản tốt trong quá trình vận chuyển", 0),
    ("Hàng về đúng hẹn mặc dù địa chỉ xa", 0),
    ("Shop có tư vấn sản phẩm phù hợp", 0),
    ("Cảm ơn shop đã hỗ trợ đổi size", 0),
    ("Phản hồi tin nhắn nhanh, tư vấn nhiệt tình", 0),
    ("Shop uy tín, hàng chính hãng, có tem niêm phong", 0),
    ("Freeship toàn quốc, mua thoải mái", 0),
    ("Thanh toán an toàn, không lo lộ thông tin", 0),
    ("Tính năng hoạt động đúng như mô tả", 0),
    ("Cài đặt dễ dàng, không cần kỹ thuật cao", 0),
    ("Dùng thử rất ổn, không có vấn đề gì", 0),
    ("Thích thiết kế hiện đại, sang trọng", 0),
    ("Màu sắc trẻ trung, hợp thời trang", 0),
    ("Chất liệu thân thiện môi trường", 0),
    ("Bền đẹp theo thời gian", 0),
    ("Mua 2 cái, cái nào cũng tốt", 0),
    ("Giá phải chăng, mua ngay không ngần ngại", 0),
    ("Combo tiết kiệm, mua nhiều lại rẻ hơn", 0),
    ("Deal ngày 11/11 quá hời", 0),
    ("Ưu đãi thành viên VIP thật sự đáng", 0),
    ("Điểm thưởng tích lũy dùng được nhiều", 0),
    ("Nhận được quà tặng kèm, bất ngờ lắm", 0),
    ("Có tem hologram chống hàng giả", 0),
    ("Hóa đơn đầy đủ, bảo hành dài", 0),
    ("Bảo hành 12 tháng, an tâm sử dụng", 0),
    ("Có thể trả góp lãi suất 0%", 0),
    ("Giao hàng tận tay, không phải ra bưu cục", 0),
    ("Shipper thân thiện, giao đúng giờ", 0),
    ("Đặt trưa, chiều đã có hàng", 0),
    ("Nhanh hơn dự kiến 1 ngày", 0),
    ("Hàng đặt hôm qua sáng nay đã có", 0),

    # ─── TOXIC (label=1) ────────────────────────────────────────────────────────
    ("Hàng rác, shop lừa đảo đồ chó", 1),
    ("Đồ shit, mua về chỉ để vứt thùng rác", 1),
    ("Shop ngu, bán hàng dởm", 1),
    ("Thằng bán hàng khốn nạn, lừa tiền", 1),
    ("Mày bán hàng gì thế, đồ rác", 1),
    ("Con bà nó, hàng như cứt", 1),
    ("Đ.m hàng tệ vl, không mua nữa", 1),
    ("Dm chất lượng tệ vãi", 1),
    ("Vcl hàng giao hỏng hết, shop tệ vl", 1),
    ("Đ.m shop lừa đảo, trả tiền lại đây", 1),
    ("Bán hàng như cc, chất lượng thảm họa", 1),
    ("Mua về như mua shit, vứt luôn", 1),
    ("Shop đồ ngu, bán đồ ăn hại", 1),
    ("Lừa đảo, hàng giả mà bán giá thật", 1),
    ("Thứ rác rưởi, chỉ biết lừa người", 1),
    ("Tên shop phải đặt là 'Hàng Nát'", 1),
    ("Đi mà ăn cứt đi, bán hàng thế này", 1),
    ("Mày tưởng mày bán hàng ngon à, rác hết", 1),
    ("Chửi mày một phát, hàng tệ quá", 1),
    ("Thứ đồ chó này mà dám bán giá cao", 1),
    ("Hàng hỏng toàn bộ, shop ngu si", 1),
    ("Đồ dỏm, bán hàng như kẻ lừa đảo", 1),
    ("Mua về muốn nổi điên, hàng hỏng hết", 1),
    ("Cút đi mà bán hàng chỗ khác", 1),
    ("Thứ này rác hơn cả rác, ghê tởm", 1),
    ("Bỏ tiền mua shit về nhà", 1),
    ("Chất lượng như cái đầu óc của mày", 1),
    ("Đồ ăn hại không xứng đáng được bán", 1),
    ("Shop này toàn mấy đứa lừa đảo", 1),
    ("Hàng mày bán như đồ bỏ đi", 1),
    ("Xấu hổ không khi bán hàng tệ thế", 1),
    ("Chỉ biết ăn tiền rồi ship rác về", 1),
    ("Gian hàng nát, bán hàng giả", 1),
    ("Mua một lần muốn kiện shop luôn", 1),
    ("Đồ phế liệu còn hơn hàng mày bán", 1),
    ("Hàng tệ như người bán vậy", 1),
    ("Thằng bán hàng bịp bợm", 1),
    ("Con nhà bán hàng láo toét", 1),
    ("Xấu tính, bán hàng lừa đảo", 1),
    ("Nghề bán hàng mà không ra gì", 1),
    ("Phá tiền người ta thôi", 1),
    ("Hàng giả trơ trẽn còn dám bán", 1),
    ("Mặt dày bán hàng nát như vậy", 1),
    ("Khốn kiếp, lấy tiền người ta rồi giao đồ hỏng", 1),
    ("Địt mẹ hàng nát, đéo mua nữa", 1),
    ("Cmm hàng này tệ vcl", 1),
    ("Đmm bán hàng lừa đảo", 1),
    ("Ngu vl còn bán hàng", 1),
    ("Hàng cứt, shop cứt, mọi thứ đều cứt", 1),
    ("Bán hàng như thằng điên", 1),
    ("Phải tâm thần mới mua hàng này", 1),
    ("Đồ cùi bắp, vứt vào thùng rác luôn", 1),
    ("Mua về chỉ để chửi bới", 1),
    ("Mày bán hàng rác thế này mà không xấu hổ", 1),
    ("Tiền tôi bỏ ra để mua thứ này là hối hận", 1),
    ("Hàng như đồ thải loại", 1),
    ("Tởm lợm, không bao giờ quay lại", 1),
    ("Ngu như chó còn bán hàng", 1),
    ("Đồ thối, bán hàng thối", 1),
    ("Shop bán hàng mà không có não", 1),
    ("Phế vật hơn cả phế vật", 1),
    ("Kiểu bán hàng này chỉ có lũ lừa đảo mới làm", 1),
    ("Mày tưởng tao ngu không biết hàng giả à", 1),
    ("Thứ đồ chó đẻ này còn bán được", 1),
    ("Bán hàng rác cho người ta là sao", 1),
    ("Chất lượng như bùn đất", 1),
    ("Mấy thằng bán hàng nát này tởm thật", 1),
    ("Hàng giao về hỏng hết mà không xin lỗi, thứ vô giáo dục", 1),
    ("Vô học mới bán hàng kiểu này", 1),
    ("Đầu óc rỗng mới bán hàng như thế", 1),
    ("Chưa thấy shop nào tệ như shop này", 1),
    ("Hàng tệ, người bán tệ, tất cả đều tệ", 1),
    ("Mua phải hàng này xui cả ngày", 1),
    ("Lần sau không bao giờ mua ở shop cứt này nữa", 1),
    ("Tiêu tiền vào đây là mất trắng", 1),
    ("Thứ rác này mà bán 500k", 1),
    ("Bán đồ giả mà không biết ngượng", 1),
    ("Hàng như đồ bỏ đi còn mang ra bán", 1),
    ("Xấu hổ chưa khi bán thứ này", 1),
    ("Đồ tệ nhất từ trước đến nay mình mua", 1),
    ("Vô trách nhiệm hoàn toàn", 1),
    ("Ăn tiền không từ tâm", 1),
    ("Mấy đứa lừa đảo chuyên nghiệp", 1),
    ("Tởm cái shop này lắm", 1),
    ("Bán hàng như kẻ trộm cướp", 1),
    ("Mua về nuối tiếc suốt", 1),
    ("Không xứng đáng được 1 sao", 1),
    ("Ghét cái shop này cực kỳ", 1),
    ("Thứ đồ bỏ đi mà bán giá trời", 1),
    ("Mày nghĩ tao làm ra tiền dễ không", 1),
    ("Chiều khách kiểu gì thế, thái độ tệ vãi", 1),
    ("Cộc lốc vô lễ, bán hàng không ra gì", 1),
    ("Trả lời tin nhắn như đù, thái độ tệ", 1),
    ("Không trả lời gì hết rồi ship hàng hỏng", 1),
    ("Phục vụ như chó, mua 1 lần không mua nữa", 1),
    ("Hỗ trợ khách hàng như thứ vô dụng", 1),
    ("Báo hỏng không chịu đổi, shop rác", 1),
    ("Chơi khăm khách hàng thế này à", 1),
    ("Xúc phạm người mua hàng rồi block luôn", 1),
    ("Dọa nạt khách hàng, shop mất dạy", 1),
    ("Bán hàng mà không có tư cách", 1),
    ("Đồ nát bét, gian hàng nát không kém", 1),
    ("Hàng như rác mà bán như vàng", 1),
    ("Đặt hàng bị lừa sạch tiền", 1),
    ("Tiền mất tật mang", 1),
    ("Mua phải hàng nhái, bực quá", 1),
    ("Hàng nhái rẻ tiền bán giá hàng xịn", 1),
    ("Không tôn trọng khách hàng chút nào", 1),
    ("Bán hàng mà dám nói xấu khách", 1),
    ("Ăn tiền người ta rồi mất hút", 1),
    ("Lừa đảo trắng trợn không hổ thẹn", 1),
    ("Shop bán hàng giả mà không biết ngượng", 1),
    ("Hàng cũ đội lốt hàng mới", 1),
    ("Hàng hết hạn mà vẫn bán", 1),
    ("Đóng gói tệ, hàng vỡ hết, không xin lỗi", 1),
    ("Bán một nhưng giao sản phẩm khác", 1),
    ("Ảnh thật và ảnh quảng cáo khác nhau hoàn toàn", 1),
    ("Gian lận, lừa người tiêu dùng", 1),
    ("Bán sản phẩm giả mạo thương hiệu", 1),
    ("Hàng không có nguồn gốc, không rõ xuất xứ mà bán giá cao", 1),
    ("Không trả hàng không hoàn tiền dù hàng lỗi", 1),
    ("Từ chối đổi trả vô lý", 1),
    ("Tiền thối lại thiếu mà không nhận lỗi", 1),
    ("Thái độ xấc láo với khách hàng", 1),
    ("Phân biệt đối xử với khách", 1),
    ("Chém khách hàng thẳng mặt", 1),
    ("Tự dưng block khách không lý do", 1),
    ("Giao hàng trễ cả tuần mà không xin lỗi", 1),
    ("Bắt chờ cả tháng rồi ship đồ nát", 1),
    ("Đặt hàng 2 tuần chưa thấy hàng đâu", 1),
    ("Không cập nhật tracking, liên hệ không trả lời", 1),
    ("Mất hàng giữa đường không bồi thường", 1),

    # ─── SPAM (label=2) ─────────────────────────────────────────────────────────
    ("Liên hệ mua hàng 0909123456", 2),
    ("Inbox mình để mua giá rẻ hơn 0987654321", 2),
    ("zalo 0912345678 để được giá tốt hơn", 2),
    ("nhắn tin số 0901234567 tư vấn miễn phí", 2),
    ("gọi ngay 1800xxxx nhận ưu đãi", 2),
    ("mua hàng giá sỉ call 0899123456", 2),
    ("có hàng xịn liên hệ t 0988123456", 2),
    ("sdt 0977123456 để hỏi thêm về sp", 2),
    ("tôi có sp tương tự giá rẻ hơn zalo 0966123456", 2),
    ("liên hệ fb.com/abc để mua hàng", 2),
    ("click vào link này để nhận quà http://bit.ly/xxxxx", 2),
    ("truy cập website của tôi để mua hàng rẻ hơn", 2),
    ("mua hàng tại shop khác rẻ hơn 50%", 2),
    ("aaaaaaaaaaaaaaaaaaaaaaaaaaaa", 2),
    ("hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh", 2),
    ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 2),
    ("test test test test test test", 2),
    ("abc abc abc abc abc abc abc", 2),
    ("1111111111111111111111111111", 2),
    ("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!", 2),
    ("???????????????????????????????????", 2),
    (".................................................", 2),
    ("   ", 2),
    ("......", 2),
    ("123456789012345678901234567890", 2),
    ("mua hàng nơi khác rẻ hơn nhieu lam", 2),
    ("tôi bán hàng tương tự ib mình nha", 2),
    ("ai cần mua comment ib mình", 2),
    ("cần bán lại máy cũ giá rẻ ib", 2),
    ("thanh lý máy còn bảo hành ib zalo", 2),
    ("follow page mình có nhiều hàng rẻ", 2),
    ("like page để nhận ưu đãi mỗi ngày", 2),
    ("sub kênh youtube để xem review thật", 2),
    ("tham gia group facebook để nhận deal hot", 2),
    ("add friend mình để được báo giá", 2),
    ("đăng ký email nhận 50% voucher", 2),
    ("click here to get free voucher now", 2),
    ("win iphone 15 free click now", 2),
    ("congratulations you won a prize", 2),
    ("bạn đã trúng thưởng click vào link", 2),
    ("cơ hội kiếm tiền online tại nhà", 2),
    ("kiếm 10 triệu mỗi ngày không cần vốn", 2),
    ("làm việc tại nhà thu nhập cao liên hệ", 2),
    ("tuyển cộng tác viên bán hàng online", 2),
    ("mời tham gia mô hình kinh doanh mới", 2),
    ("đầu tư 5 triệu lợi nhuận 50 triệu mỗi tháng", 2),
    ("crypto bitcoin đầu tư ngay hôm nay", 2),
    ("nạp tiền nhận thưởng gấp 10 lần", 2),
    ("game bài uy tín nạp rút 24/7", 2),
    ("casino online tỷ lệ thắng cao", 2),
    ("cho vay tiền nhanh không cần thế chấp", 2),
    ("vay tiền online giải ngân trong ngày", 2),
    ("tôi tên là John đến từ Mỹ cần chuyển 1 triệu đô", 2),
    ("bán acc game giá rẻ liên hệ", 2),
    ("hack acc không giới hạn xu game", 2),
    ("phần mềm crack full version free download", 2),
    ("tool hack game kiếm xu không giới hạn", 2),
    ("auto click farm xu game miễn phí", 2),
    ("hàng xách tay Mỹ giá rẻ ib ngay", 2),
    ("order hàng Mỹ Nhật giá tốt ib", 2),
    ("ship hàng từ Mỹ về VN giá ưu đãi", 2),
    ("bán hàng trung quốc giá rẻ vcl ib", 2),
    ("hàng si giá sỉ từ 10 cái ib", 2),
    ("nhận order hàng độc lạ từ Nhật", 2),
    ("bán sỉ mỹ phẩm nhập khẩu ib báo giá", 2),
    ("tuyển đại lý mỹ phẩm hoa hồng cao", 2),
    ("multi level marketing thu nhập thụ động", 2),
    ("giảm 90% chỉ hôm nay thôi", 2),
    ("miễn phí 100% chỉ cần share", 2),
    ("share bài này nhận quà ngay", 2),
    ("tag 3 bạn bè nhận voucher 500k", 2),
    ("comment số điện thoại nhận quà", 2),
    ("bình luận tên bạn để nhận phần thưởng", 2),
    ("minigame thả tim nhận code", 2),
    ("săn mã giảm giá miễn phí tại đây", 2),
    ("mã code giảm 50% nhập SPAM50", 2),
    ("nhập code FAKE100 giảm ngay 100k", 2),
    ("quét QR nhận tiền miễn phí", 2),
    ("tải app nhận 200k tiền mặt ngay", 2),
    ("cài app ngay nhận ưu đãi lần đầu", 2),
    ("đăng ký tài khoản nhận thưởng 500k", 2),
    ("mời bạn bè nhận hoa hồng không giới hạn", 2),
    ("referral code của tôi xxx nhập để nhận quà", 2),
    ("ưu đãi khủng không tưởng chỉ hôm nay", 2),
    ("số lượng có hạn mua ngay kẻo hết", 2),
    ("chỉ còn 1 sản phẩm cuối cùng mua ngay", 2),
    ("flash sale 0 đồng chỉ trong 1 giờ", 2),
    ("deal sốc mua ngay trước khi hết", 2),
    ("sản phẩm bán chạy nhất hôm nay xem ngay", 2),
    ("top 1 bán chạy tháng này không thể bỏ qua", 2),
    ("hàng trending 2024 mua trước đón sóng", 2),
    ("review fake của shop tôi cần mua", 2),
    ("cần người viết review tốt cho shop", 2),
    ("thuê viết review 5 sao trả tiền ngay", 2),
    ("dịch vụ tăng like review uy tín", 2),
    ("tăng đánh giá sao cho shop bán giá rẻ", 2),
    ("mua đánh giá 5 sao giá tốt liên hệ", 2),
    ("dịch vụ tăng follow page shop", 2),
    ("tăng view sản phẩm trên sàn uy tín", 2),
    ("seeding đánh giá số lượng lớn", 2),
    ("tôi thấy hàng này bên shop khác rẻ hơn đây", 2),
    ("không mua ở đây mua ở chỗ tôi rẻ hơn", 2),
    ("bên tôi có hàng tương tự giá chỉ bằng nửa", 2),
    ("spam spam spam spam spam", 2),
    ("mua bán trao đổi ib zalo 0xxx", 2),
    ("nhận đặt hàng số lượng lớn chiết khấu cao", 2),
    ("giao dịch riêng ngoài sàn giá tốt hơn", 2),
    ("mua bán ngoài app để tiết kiệm phí", 2),
    ("chuyển khoản trực tiếp để được giảm thêm", 2),
    ("mua hàng qua zalo để rẻ hơn 30%", 2),
    ("không mua trên app vô zalo mua", 2),
    ("tôi ship tay từ Hàn Quốc ib tư vấn", 2),
    ("order Taobao giá gốc không lợi nhuận", 2),
    ("hàng Quảng Châu chất lượng cao ib", 2),
    ("thanh lý toàn bộ đồ điện tử giá rẻ", 2),
    ("dọn kho bán rẻ 50% ib ngay", 2),
    ("cần tiền gấp bán rẻ toàn bộ", 2),
    ("bán để trả nợ giá cực rẻ ib", 2),
    ("chuyển nhà bán tất cả đồ giá hời", 2),
    ("quà tặng free chỉ cần trả phí ship nhỏ", 2),
    ("tặng miễn phí chỉ trả 20k ship thôi", 2),
    ("sản phẩm free không mất tiền chỉ ship", 2),
    ("đổi điểm thưởng lấy quà miễn phí ngay", 2),
    ("spin wheel nhận quà miễn phí mỗi ngày", 2),
    ("check in nhận xu miễn phí", 2),
    ("bình luận gì cũng được để nhận quà", 2),
    ("đây là comment thử xem có duyệt không", 2),
    ("testing moderation system 123", 2),
    ("xin chào tôi muốn mua hàng 0901111111", 2),
    ("bán sp này với giá tốt hơn 0902222222", 2),
    ("shopee mall giả fake không nên mua", 2),
    ("hàng chính hãng giả giá thật lừa đảo", 2),
    ("phân phối độc quyền fake ib", 2),
    ("địa chỉ shop thật của tôi tại 123 đường abc", 2),
    ("bán trực tiếp không qua sàn giá rẻ hơn", 2),
    ("mua offline tại cửa hàng để được giảm thêm", 2),
    ("ghé cửa hàng mình tại quận 1 để mua", 2),
    ("kho xưởng tận gốc giá sỉ hơn shop này", 2),
    ("tôi là nhà sản xuất trực tiếp inbox", 2),
    ("nhà máy trực tiếp xuất khẩu giá tốt", 2),
    ("bán buôn số lượng lớn liên hệ ngay", 2),
    ("hàng container giá sỉ tốt call ngay", 2),
    ("nhập hàng trực tiếp không qua trung gian", 2),
    ("giá đại lý cấp 1 ib để biết thêm", 2),
    ("mua số lượng nhiều được chiết khấu 40%", 2),
    ("combo 10 cái giá chỉ bằng 3 cái", 2),
    ("mua 5 tặng 5 inbox để biết thêm", 2),
    ("điều khoản ưu đãi đặc biệt inbox mình", 2),
    ("hợp tác kinh doanh lợi nhuận chia đều", 2),
    ("đại lý toàn quốc tuyển gấp", 2),
    ("franchise nhượng quyền giá rẻ", 2),
    ("đầu tư mô hình kinh doanh mới siêu lợi nhuận", 2),
    ("không cần vốn vẫn kiếm tiền mỗi ngày", 2),
    ("học cách kiếm tiền online miễn phí", 2),
    ("khóa học kinh doanh online miễn phí", 2),
    ("tham gia cộng đồng kiếm tiền online", 2),
    ("nhóm kín kiếm tiền thật invite link", 2),
    ("discount code SHOP50 giảm ngay", 2),
    ("voucher 200k cho đơn từ 300k code xxx", 2),
    ("mã giới thiệu của tôi abc123 nhập nhận quà", 2),
    ("affiliate link nhận hoa hồng mỗi đơn hàng", 2),
    ("kiếm tiền từ affiliate marketing dễ dàng", 2),
    ("hướng dẫn kiếm tiền dropship không vốn", 2),
    ("bán hàng không cần nhập hàng dropship", 2),
    ("cộng tác viên bán hàng online không vốn", 2),
    ("làm CTV nhận hoa hồng 30% mỗi đơn", 2),
    ("tuyển ctv bán mỹ phẩm online", 2),
    ("tuyển ctv bán hàng thời trang online", 2),
    ("bán online tại nhà thu nhập ổn định", 2),
    ("kinh doanh online tại nhà không cần ra ngoài", 2),

    # ─── More SAFE ──────────────────────────────────────────────────────────────
    ("Rất hài lòng, đúng mô tả, giao nhanh", 0),
    ("Sản phẩm bền đẹp, đáng mua", 0),
    ("Giá rẻ nhất thị trường mà chất lượng ổn", 0),
    ("Mua lần đầu sẽ không phải lần cuối", 0),
    ("Hàng về nhanh, đúng mẫu, hài lòng", 0),
    ("Sản phẩm tốt, đóng gói cẩn thận", 0),
    ("Mình thích lắm, dùng rất tốt", 0),
    ("Chất lượng vượt kỳ vọng với giá tầm này", 0),
    ("Dịch vụ hậu mãi tốt, shop uy tín", 0),
    ("Lần đầu mua hàng online mà được sản phẩm tốt thế này", 0),
    ("Giao hàng cẩn thận, bọc bong bóng nhiều lớp", 0),
    ("Shipper dễ thương, giao đúng giờ", 0),
    ("Thông báo giao hàng trước, rất tiện", 0),
    ("Hàng về nguyên vẹn, không vỡ vẽ gì", 0),
    ("Sản phẩm như mô tả, không có gì phàn nàn", 0),
    ("Đúng với những gì được quảng cáo", 0),
    ("Mua nhiều lần, lần nào cũng ổn", 0),
    ("Shop giao hàng nhanh kể cả ngày lễ", 0),
    ("Tư vấn chọn size rất nhiệt tình", 0),
    ("Cho tôi đổi màu mà không tính thêm phí", 0),
    ("Hỗ trợ sau mua hàng rất tốt", 0),
    ("Cảm ơn shop đã giải quyết khiếu nại nhanh", 0),
    ("Hoàn tiền nhanh khi hàng lỗi", 0),
    ("Đổi hàng không mất phí, rất ưng", 0),
    ("Chính sách bảo hành rõ ràng, dễ thực hiện", 0),
    ("Hàng chính hãng, tem niêm phong đầy đủ", 0),
    ("Sản phẩm xịn, giá cạnh tranh", 0),
    ("Thiết kế đẹp, chắc tay", 0),
    ("Màu thực tế đẹp hơn hình", 0),
    ("Kích thước vừa vặn đúng như bảng đo", 0),
    ("Dùng 3 tháng vẫn tốt như mới", 0),
    ("Bền lắm, dùng nguyên năm chưa hỏng", 0),
    ("Không bị phai màu sau nhiều lần giặt", 0),
    ("Chất liệu cao cấp, đường chỉ may đẹp", 0),
    ("Giày không đau chân dù đi cả ngày", 0),
    ("Dép mềm thoải mái, chống trơn tốt", 0),
    ("Quần jeans đẹp, vải dày không mỏng", 0),
    ("Áo khoác ấm, chống gió tốt", 0),
    ("Váy đẹp, nhiều màu chọn", 0),
    ("Túi xách chắc chắn, khóa kéo bền", 0),
    ("Giỏ đựng nhiều đồ, nhẹ", 0),
    ("Ốp lưng bảo vệ tốt, viền chắc", 0),
    ("Miếng dán màn hình không bong", 0),
    ("Cáp lightning sạc nhanh 3.0", 0),
    ("Pin dự phòng 20000mah dùng được 5 lần sạc", 0),
    ("Tai nghe không dây pin trâu", 0),
    ("Loa mini âm thanh hay cho phòng nhỏ", 0),
    ("Webcam chất lượng HD rõ nét", 0),
    ("Bàn phím cơ switch blue gõ hay", 0),
    ("Chuột gaming DPI cao, cầm thoải mái", 0),
    ("Màn hình IPS 144Hz chơi game mượt", 0),
    ("SSD 500GB đọc ghi nhanh", 0),
    ("RAM 16GB tăng tốc máy tính rõ rệt", 0),
    ("Tủ lạnh inverter tiết kiệm điện", 0),
    ("Máy giặt cửa ngang êm, ít rung", 0),
    ("Điều hòa lạnh nhanh, tiết kiệm điện", 0),
    ("Bếp từ nấu nhanh, an toàn", 0),
    ("Nồi áp suất nấu mềm nhanh", 0),
    ("Lò vi sóng hâm nóng đều", 0),
    ("Máy pha cà phê ngon như quán", 0),
    ("Máy xay sinh tố mạnh, xay mịn", 0),
    ("Nồi chiên không dầu tiện lợi", 0),
    ("Máy hút bụi mạnh, nhẹ", 0),
    ("Bàn là hơi nước làm phẳng quần áo tốt", 0),
    ("Máy sấy tóc ion không khô tóc", 0),
    ("Máy cạo râu dùng pin bền", 0),
    ("Bàn chải điện làm sạch tốt", 0),
    ("Máy massage cổ vai gáy hiệu quả", 0),

    # ─── More TOXIC ─────────────────────────────────────────────────────────────
    ("Thứ đồ chó đẻ này không xứng đáng bán", 1),
    ("Ngu như bò còn bán hàng", 1),
    ("Đồ mày bán như đồ thải ra từ nhà máy tái chế", 1),
    ("Tiêu mất tiền vào thứ vô dụng này", 1),
    ("Mua về thấy tức muốn đập phá", 1),
    ("Chửi thề cho hả giận chứ hàng tệ thật", 1),
    ("Đồ như cứt mà bán đắt hơn cả đồ xịn", 1),
    ("Thứ phế liệu mà dám bán giá trời", 1),
    ("Mày không biết ngượng khi bán thứ này à", 1),
    ("Shop này cần đóng cửa luôn đi", 1),
    ("Tất cả những gì shop bán đều là rác", 1),
    ("Mua đồ mày về là mất tiền oan", 1),
    ("Bán hàng giả mà không biết xấu hổ", 1),
    ("Hàng nhái rẻ tiền bán giá hàng xịn nghe được không", 1),
    ("Không tôn trọng người mua thì đừng bán", 1),
    ("Đồ phế phẩm không hơn không kém", 1),
    ("Chất lượng như đồ bỏ đi cọng rác", 1),
    ("Shop lừa đảo cần bị report sàn", 1),
    ("Hàng này dành cho những kẻ thích bị lừa", 1),
    ("Đặt hàng về nhận được cục rác", 1),
    ("Mày nghĩ mày bán hàng hay lắm à", 1),
    ("Thứ rác rưởi này xứng đáng bị vứt", 1),
    ("Không có não mới mua hàng này lần 2", 1),
    ("Hàng giả cực phẩm mà bán giá hàng xịn", 1),
    ("Tiền đâu dễ kiếm mà mua thứ như vậy", 1),

    # ─── More SPAM ──────────────────────────────────────────────────────────────
    ("contact: spam@email.com for more info", 2),
    ("whatsapp: +84901234567", 2),
    ("telegram: @spamaccount", 2),
    ("discord: spamuser#1234", 2),
    ("instagram: @fake_shop_viet", 2),
    ("tiktok: @banhang_online_xyz", 2),
    ("youtube.com/channel/fakeshop", 2),
    ("fb.me/fakepage", 2),
    ("bit.ly/getnow", 2),
    ("tinyurl.com/fakeoffer", 2),
    ("hãy ghé thăm website của tôi", 2),
    ("giảm giá đặc biệt chỉ hôm nay", 2),
    ("mã giảm giá FIRST100 áp dụng ngay", 2),
    ("nhập code nhận quà ngay tức thì", 2),
    ("mua ngay nhận ngay không chờ đợi", 2),
    ("ưu đãi sốc chỉ dành cho bạn", 2),
    ("bạn được chọn để nhận phần thưởng đặc biệt", 2),
    ("chúc mừng bạn đã trúng thưởng", 2),
    ("xác nhận email để nhận giải thưởng", 2),
    ("gửi thông tin cá nhân để nhận quà", 2),
    ("điền form để nhận voucher miễn phí", 2),
    ("survey ngắn nhận tiền thưởng 200k", 2),
    ("làm khảo sát 5 phút nhận 100k ngay", 2),
    ("review để nhận tiền thưởng từ shop", 2),
    ("đánh giá 5 sao nhận 50k qua ví", 2),
    ("chụp bill gửi shop nhận hoàn tiền", 2),
    ("feedback để nhận mã giảm giá lần sau", 2),
    ("chia sẻ đơn hàng nhận xu thưởng", 2),
    ("mời bạn bè nhận hoa hồng", 2),
    ("giới thiệu 1 người nhận 100k", 2),
    ("chuỗi ký tự vô nghĩa: qwerty uiop asdf", 2),
    ("random text here nothing important", 2),
    ("lorem ipsum dolor sit amet", 2),
    ("blah blah blah blah blah", 2),
    ("ngdnakjdnakjdnakjdna", 2),
    ("xyzxyzxyzxyzxyzxyz", 2),
    ("0000000000000000000000", 2),
    ("9999999999999999999", 2),
    ("abcdefghijklmnopqrstuvwxyz", 2),
    ("aabbccddee fgghh iijjkk", 2),
]


def get_texts_and_labels() -> tuple[list[str], list[int]]:
    """Trả về (texts, labels) từ seed data."""
    texts = [item[0] for item in SEED_DATA]
    labels = [item[1] for item in SEED_DATA]
    return texts, labels
